events {}

http {
    server {
        listen 80;

        location /stakeholders/ {
            proxy_pass http://stakeholders:8080/;
        }

        location /blog/ {
            proxy_pass http://blog:8080/;
        }

        location /followers/ {
            proxy_pass http://followers:8082/;
        }

        location = /tours/swagger/index.html {
            return 302 /tours/swagger-ui/index.html?configUrl=/tours/v3/api-docs/swagger-config;
        }

        location = /tours/swagger {
            return 302 /tours/swagger-ui/index.html?configUrl=/tours/v3/api-docs/swagger-config;
        }

        location = /tours/v3/api-docs/swagger-config {
            default_type application/json;
            return 200 '{"configUrl":"/tours/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8000/tours/swagger-ui/oauth2-redirect.html","url":"/tours/v3/api-docs","validatorUrl":""}';
        }

        location /tours/ {
            proxy_pass http://tours:8083/;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /v3/api-docs/swagger-config {
            default_type application/json;
            return 200 '{"configUrl":"/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8000/tours/swagger-ui/oauth2-redirect.html","url":"/v3/api-docs","validatorUrl":""}';
        }

        location = /v3/api-docs {
            proxy_pass http://tours:8083/v3/api-docs;
        }
    }
}