spring.application.name=tours-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5435/tours_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=L1uKpZQzI1Yx0+OaS0kXkE7u0n/5Q0U3R5s3FVmXcXU=
jwt.issuer=stakeholder
jwt.audience=stakeholder-front.com

server.forward-headers-strategy=framework